import {
  TreePine, Trash2, AlertTriangle, Sparkles, Armchair, Cigarette,
  HardHat, Waves, Palette, BatteryWarning, Sprout, Paintbrush,
  Flame, Zap, BadgeCheck, Globe, Building2, Users, Trophy, Gem,
  Medal, Award, Star, MapPin, Coffee, Ticket, UtensilsCrossed,
  Recycle, Droplets, Crown, Bell, Search, Leaf, CheckCircle,
  AlertCircle, Camera, Loader2, CircleCheck, CircleX, Bot,
  Satellite, Lock, type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  "tree-pine": TreePine,
  "trash": Trash2,
  "alert-triangle": AlertTriangle,
  "sparkles": Sparkles,
  "armchair": Armchair,
  "cigarette": Cigarette,
  "hard-hat": HardHat,
  "waves": Waves,
  "palette": Palette,
  "battery-warning": BatteryWarning,
  "sprout": Sprout,
  "paintbrush": Paintbrush,
  "flame": Flame,
  "zap": Zap,
  "badge-check": BadgeCheck,
  "globe": Globe,
  "building": Building2,
  "users": Users,
  "trophy": Trophy,
  "gem": Gem,
  "medal": Medal,
  "award": Award,
  "star": Star,
  "map-pin": MapPin,
  "coffee": Coffee,
  "ticket": Ticket,
  "utensils": UtensilsCrossed,
  "recycle": Recycle,
  "droplets": Droplets,
  "crown": Crown,
  "bell": Bell,
  "search": Search,
  "leaf": Leaf,
  "check-circle": CheckCircle,
  "alert-circle": AlertCircle,
  "camera": Camera,
  "loader": Loader2,
  "circle-check": CircleCheck,
  "circle-x": CircleX,
  "bot": Bot,
  "satellite": Satellite,
  "lock": Lock,
};

export default function DataIcon({ name, size = 16, ...props }: { name: string; size?: number; [key: string]: any }) {
  const Comp = MAP[name];
  if (!Comp) return <span>{name}</span>;
  return <Comp size={size} strokeWidth={1.8} {...props} />;
}
