replicaCount: 1

image:
  repository: acrchistdev.azurecr.io/chist-notification
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "notification-module"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8082

ingress:
  enabled: false

resources:
  requests:
    cpu: 75m
    memory: 64Mi
  limits:
    cpu: 300m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8082
  initialDelaySeconds: 90
  periodSeconds: 15
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8082
  initialDelaySeconds: 90
  periodSeconds: 15
  failureThreshold: 5

autoscaling:
  enabled: false

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

envFrom:
  - secretRef:
      name: backend-secret

httpRoute:
  enabled: false
