apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://registry-1.docker.io/bitnamicharts
    chart: rabbitmq
    targetRevision: 16.0.14
    helm:
      values: |
        global:
          imageRegistry: acrchistdev.azurecr.io
          security:
            allowInsecureImages: true
        auth:
          username: chist
          existingPasswordSecret: rabbitmq-secret
          existingSecretPasswordKey: RABBITMQ_PASSWORD
        persistence:
          enabled: true
          size: 1Gi
        service:
          type: ClusterIP
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true