apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-module
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/TUES-2026-PBL-11-klas/Grupa-Lom-Project2-Chist
    targetRevision: main
    path: helm/user-module-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: chist
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
