replicaCount: 1
image:
  repository: acrchistdev.azurecr.io/chist-frontend-next
  pullPolicy: Always
  tag: "latest"
containerPort: 3000
env:
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
  BACKEND_URL: "http://user-module:8080"
  AUTH_COOKIE_SECURE: "true"
  NEXT_PUBLIC_DEFAULT_LOCALE: "bg"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: "4.165.174.62.nip.io"
      paths:
        - path: /
          pathType: Prefix
          servicePort: 80
  tls: []
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
livenessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 5
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
httpRoute:
  enabled: false
