replicaCount: 1
image:
  repository: acrchistdev.azurecr.io/chist-frontend
  pullPolicy: Always
  tag: "latest"
env:
  VITE_API_URL: "http://user-module:8080"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: "4.165.174.62.nip.io"
      paths:
        - path: /
          pathType: Prefix
          servicePort: 80
  tls: []
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
livenessProbe: {}
readinessProbe: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
httpRoute:
  enabled: false
